# Generated by Django 2.2.9 on 2020-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('target', models.TextField(verbose_name='Intervalo de ativos')),
                ('status', models.IntegerField(choices=[(-10, 'Cancelado'), (-5, 'Erro no Scan'), (0, 'não Criado'), (5, 'em Andamento'), (10, 'Completo'), (15, 'Aguardando Dowload'), (20, 'Baixando Scan'), (25, 'Em Processamento'), (30, 'Finalizado')], default=0, verbose_name='Status')),
            ],
        ),
    ]
